openapi: 3.0.1
info:
  title: API V1
  version: v1
servers:
- url: http://localhost:3000/api/v1
  variables:
    defaultHost:
      default: www.example.com
tags:
  - name: author
    description: Everything about your author
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths: 
  /author/{authorId}:
    get:
      tags:
        - author
      summary: Find an Author by ID
      operationId: getAhthorById
      parameters:
        - name: authorId
          in: path
          description: ID of Author to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '400':
          description: Invalid ID supplied
        '404':
          description: Auhor Not Found
      security: 
        - bearer: []
components:
  schemas:
    Author:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: 宮沢賢治
        createdAt:
          type: string
          format: data-time
          example: 2017-07-21T17:32:28Z
        updateAt:
          type: string
          format: data-time
          example: 2017-07-21T17:32:28Z
  securitySchemes:
    bearer:
      type: http
      description: JWT Token Authenticatio
      scheme: bearer
      bearerFormat: JWT

