default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'postgres' } %>

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { '' } %>

test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { '' } %>

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { '' } %>
